site_name: Kano Docs

repo_url: https://github.com/egliette/kano
repo_name: egliette/kano

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  palette:
    primary: pink
  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.prune
    - navigation.footer
    - navigation.tracking
    - navigation.instant
    - navigation.instant.progress
    - navigation.indexes
    - navigation.sections

nav:
  - Home:
    - index.md
    - Common utilities:
        - common/index.md
        - Image: common/image_utils.md
        - Video: common/video_utils.md
        - File: common/file_utils.md
    - Computer Vision tasks:
        - cv/index.md
        - Dataset: cv/dataset_utils.md
        - Object detection: cv/detect_utils.md

  - Common:
    - common/index.md
    - Image: common/image_utils.md
    - Video: common/video_utils.md
    - File: common/file_utils.md

  - Computer Vision:
    - cv/index.md
    - Dataset: cv/dataset_utils.md
    - Object detection: cv/detect_utils.md
    - Profiling: cv/profiler.md
    - Source reader: cv/source_reader.md


markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
- search
- mkdocstrings:
    enabled: true
    default_handler: python
    handlers:
      python:
        options:
          docstring_style: google
          show_root_heading: true
          show_source: true

extra_css:
  - overrides/stylesheets/style.css
